configure ^
	-opensource ^
	-nomake examples ^
	-nomake tests ^
	-confirm-license ^
	-c++11 ^
	-no-sql-sqlite ^
	-mp ^
	-debug ^
	-platform win32-msvc2013 ^
	-opengl desktop ^
	-no-angle ^
	-no-icu ^
	-skip qt3d ^
	-skip qtcanvas3d ^
	-skip qtmultimedia ^
	-skip qtpim ^
	-skip qtqa ^
	-skip qtquick1 ^
	-skip qtquickcontrols ^
	-skip qtscript ^
	-skip qtsensors ^
	-skip qtserialport ^
	-skip qtsvg ^
	-skip qtwebchannel ^
	-skip qtwebengine ^
	-skip qtwebkit ^
	-skip qtwebkit-examples ^
	-skip qtwebsockets ^
	-skip qttools ^
	-skip qtdeclarative ^
	-skip qtlocation ^
	-skip qtxmlpatterns ^
	-skip qtwinextras
	