configure ^
	-opensource ^
	-nomake examples ^
	-nomake tests ^
	-confirm-license ^
	-c++11 ^
	-no-sql-sqlite ^
	-mp ^
	-debug-and-release ^
	-platform win32-msvc2015 ^
	-opengl desktop ^
	-no-angle ^
	-no-icu ^
	-prefix qt5install ^
	-skip qtandroidextras ^
	-skip qtmacextras ^
	-skip qtx11extras ^
	-skip qtsvg ^
	-skip qtxmlpatterns ^
	-skip qtdeclarative ^
	-skip qtquickcontrols ^
	-skip qtmultimedia ^
	-skip qtwinextras ^
	-skip qtactiveqt ^
	-skip qtsystems ^
	-skip qtlocation ^
	-skip qtsensors ^
	-skip qtconnectivity ^
	-skip qtfeedback ^
	-skip qtpim ^
	-skip qtwebsockets ^
	-skip qtwebchannel ^
	-skip qtwebkit ^
	-skip qttools ^
	-skip qtwebkit-examples ^
	-skip qtimageformats ^
	-skip qt3d ^
	-skip qtcanvas3d ^
	-skip qtgraphicaleffects ^
	-skip qtscript ^
	-skip qtquick1 ^
	-skip qtdocgallery ^
	-skip qtwayland ^
	-skip qtserialport ^
	-skip qtenginio ^
	-skip qtwebengine ^
	-skip qttranslations ^
	-skip qtdoc ^
	-skip qtqa 
	
